[package]
name = "worker"
version.workspace = true
edition.workspace = true

[dependencies]
shared-config = { path = "../../crates/shared-config" }
shared-db = { path = "../../crates/shared-db" }
shared-observability = { path = "../../crates/shared-observability" }
notifications = { path = "../../crates/notifications" }
payments = { path = "../../crates/payments" }

tokio = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
