[package]
name = "dashboard"
version.workspace = true
edition.workspace = true

[dependencies]
shared-auth = { path = "../shared-auth" }
shared-http = { path = "../shared-http" }

axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
