[package]
name = "reporting"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
validator = { workspace = true }
shared-http = { path = "../shared-http" }
